### ISSUE TITLE
extensions slows down and cannot grab images on onlyfans 

### ISSUE THREAD

**Issue by Kvothe1970** [kisdma/image-downloader-cnt#8]
After loading a page with about 650 images. Clicking on the extension causes the popup to show, but only bit by bit. The extension barely reacts for some reason on onlyfans. It cannot find the images behind the thumbnails at this point. The only extension found those, but stopped working a while ago. Is there anything you can do grab the images from the links? 

The slowness can be reproduced. 

The inability to grab the images from the links only, seems to be limites to the grid view. If that is switched to the view with the images in one long continuous view one after the other, the extension can grab the images from the links. Maybe something worth looking into.

**Comment by kisdma** [comment]
Hi Kvothe1970,

Thank you for the report and suggestions! Could you please provide an example page(s) for me to test on?

I'm aware of the problem when there are a lot of large high-res images loading in the popup window - they are loading slow and eventually the popup process may crush. I have a few ideas how to overcome this, and I'm testing them now. Hope there will be a solution soon!

I agree that it would be nice to add an image discovery by following links from the current page. I plan to implement it but it may worsen the above problem, so I want to fix it first.

**Comment by Kvothe1970** [comment]
Hi, I would love to assist. Can we take this to a private convo? Obviously you would need an account to try this out so maybe we can work something out for you to troubleshoot.

**Comment by kisdma** [comment]
Hi Kvothe1970,
Sure, use gmail or hangouts please to contact me kisdma
